### ISSUE TITLE
Hitting 16 mb limit

### ISSUE THREAD

**Issue by sjeps** [punkave/mongo-dump-stream#3] opened 2015-03-12 16:10 UTC
There is a bug during load.
I have a big collection of documents. Some of these are about 4mb and are loaded one after the other (i suspect incrementingg _id).

The loading ends prematurely with 16mb exception (i have no file above 16 mb)

mongorestore works on same collection

**Comment by boutell** [comment] 2015-03-12 17:00
Interesting. My guess is that this is happening because I'm waiting for a
16MB batch to try an insert, and the real limit on a batch insert is
perhaps slightly less than "total size of all documents is 16777216". But I
have no idea what that true limit really is.

Here is a good test to try:

Change 16777216 (it only appears once) in index.js and try your load again.
Reduce it to:

4194304

If that works for you I can apply it for everyone. I don't think there's
much of a win in batch insert at sizes that high anyway.

On Thu, Mar 12, 2015 at 12:10 PM, sjeps notifications@github.com wrote:

> There is a bug during load.
> I have a big collection of documents. Some of these are about 4mb and are
> loaded one after the other (i suspect incrementingg _id).
> 
> The loading ends prematurely with 16mb exception (i have no file above 16
> mb)
> 
> mongorestore works on same collection
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/mongo-dump-stream/issues/3.

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment] 2015-03-12 17:05
Also, what version of MongoDB is your server running?

On Thu, Mar 12, 2015 at 1:00 PM, Tom Boutell tom@punkave.com wrote:

> Interesting. My guess is that this is happening because I'm waiting for a
> 16MB batch to try an insert, and the real limit on a batch insert is
> perhaps slightly less than "total size of all documents is 16777216". But I
> have no idea what that true limit really is.
> 
> Here is a good test to try:
> 
> Change 16777216 (it only appears once) in index.js and try your load
> again. Reduce it to:
> 
> 4194304
> 
> If that works for you I can apply it for everyone. I don't think there's
> much of a win in batch insert at sizes that high anyway.
> 
> On Thu, Mar 12, 2015 at 12:10 PM, sjeps notifications@github.com wrote:
> 
> > There is a bug during load.
> > I have a big collection of documents. Some of these are about 4mb and are
> > loaded one after the other (i suspect incrementingg _id).
> > 
> > The loading ends prematurely with 16mb exception (i have no file above 16
> > mb)
> > 
> > mongorestore works on same collection
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/punkave/mongo-dump-stream/issues/3.
> 
> ## 
> 
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment] 2015-03-12 17:06
(I know it is allowable to upload one 16MB document. My guess is there is
overhead for each additional document which I ahve to take into account,
but the amount of overhead is undocumented. Setting a much lower threshold
is one way to be sure that won't matter.)

On Thu, Mar 12, 2015 at 1:05 PM, Tom Boutell tom@punkave.com wrote:

> Also, what version of MongoDB is your server running?
> 
> On Thu, Mar 12, 2015 at 1:00 PM, Tom Boutell tom@punkave.com wrote:
> 
> > Interesting. My guess is that this is happening because I'm waiting for a
> > 16MB batch to try an insert, and the real limit on a batch insert is
> > perhaps slightly less than "total size of all documents is 16777216". But I
> > have no idea what that true limit really is.
> > 
> > Here is a good test to try:
> > 
> > Change 16777216 (it only appears once) in index.js and try your load
> > again. Reduce it to:
> > 
> > 4194304
> > 
> > If that works for you I can apply it for everyone. I don't think there's
> > much of a win in batch insert at sizes that high anyway.
> > 
> > On Thu, Mar 12, 2015 at 12:10 PM, sjeps notifications@github.com wrote:
> > 
> > > There is a bug during load.
> > > I have a big collection of documents. Some of these are about 4mb and
> > > are loaded one after the other (i suspect incrementingg _id).
> > > 
> > > The loading ends prematurely with 16mb exception (i have no file above
> > > 16 mb)
> > > 
> > > mongorestore works on same collection
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/punkave/mongo-dump-stream/issues/3.
> > 
> > ## 
> > 
> > *THOMAS BOUTELL, *DEV & OPS
> > P'UNK AVENUE | (215) 755-1330  |  punkave.com
> 
> ## 
> 
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by sjeps** [comment] 2015-03-12 22:07
unfortunately an old 2.4 mongo server.

i can't try what you are asking at the moment, maybe next days.. also i'm not a proficient js user... should i change index.js and then "compile" ? :-)

**Comment by boutell** [comment] 2015-03-13 01:43
Hmm, if you're finding that tricky you could send me a test program that
fails.

I'm going to try to come up with one myself, but I might fail to fail (:

On Thu, Mar 12, 2015 at 6:07 PM, sjeps notifications@github.com wrote:

> unfortunately an old 2.4 mongo server.
> 
> i can't try what you are asking at the moment, maybe next days.. also i'm
> not a proficient js user... should i change index and then "compile" ? :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/mongo-dump-stream/issues/3#issuecomment-78648208
> .

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment] 2015-03-13 01:46
You could even send me a link to download a mongodump that will fail if I
restore it and then try to run it through my tools. tom@punkave.com

On Thu, Mar 12, 2015 at 9:43 PM, Tom Boutell tom@punkave.com wrote:

> Hmm, if you're finding that tricky you could send me a test program that
> fails.
> 
> I'm going to try to come up with one myself, but I might fail to fail (:
> 
> On Thu, Mar 12, 2015 at 6:07 PM, sjeps notifications@github.com wrote:
> 
> > unfortunately an old 2.4 mongo server.
> > 
> > i can't try what you are asking at the moment, maybe next days.. also i'm
> > not a proficient js user... should i change index and then "compile" ? :-)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/punkave/mongo-dump-stream/issues/3#issuecomment-78648208
> > .
> 
> ## 
> 
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment] 2015-03-15 14:31
Update: I tried to write tests to recreate this situation but the darn things keep passing. I'm going to close this for now, but if you are able to provide me with a sample file that reproduces the error, I will gladly take a look.

**Closed as completed by boutell** 2015-03-15 14:31 UTC

**Comment by onesup** [comment] 2015-05-06 06:23
me too. is that bson problem?

```
ssh deploy@mongo "mongo-dump-stream mongodb://localhost:27017/projectc_production | gzip -9" | gunzip | mongo-load-stream mongodb://localhost:27017/projectc_development
[Error: Document exceeds maximum allowed bson size of 16777216 bytes]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
```

**Comment by boutell** [comment] 2015-05-06 11:16
What I need to help you guys is a regular mongodump of a database that will
reproduce this if I run it through my tools. You can reach out to me
privately at tom@punkave.com

**Comment by yayajacky** [comment] 2015-05-19 19:08
For anyone who was stuck on this: you can get past the load issue by changing this line

In index.js ...
flushIfNeeded: function(callback) {
            if (insertQueueSize + item.length <= 16777000){//16777216) {
...

Play around with different numbers there.

**Comment by boutell** [comment] 2015-05-19 19:26
Please, please reach out to me with a dataset that reproduces the bug
instead...

**Comment by yayajacky** [comment] 2015-05-19 19:28
Sorry but the dataset I am working with is confidential, if I can reproduce this in public domain data I will respond, thanks for the good work!!

**Comment by boutell** [comment] 2015-05-19 19:32
I understand.

On Tue, May 19, 2015 at 3:28 PM, Jack Yeh notifications@github.com wrote:

> Sorry but the dataset I am working with is confidential, if I can
> reproduce this in public domain data I will respond, thanks for the good
> work!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/mongo-dump-stream/issues/3#issuecomment-103644280
> .

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by yayajacky** [comment] 2015-05-29 21:09
Ok, I think the issue is coming from the callback being hit too early.

Some of us will try to call process.exit inside the callback during dump, and this will leave the out stream incomplete with its writes, resulting in a bad bson insert during load.

I have forked the repo and close the db and wait for stream write to be complete before calling the callback.

Thanks for the good work!

**Comment by boutell** [comment] 2015-05-29 22:46
Want to send a pull request?

**Comment by eagleas** [comment] 2016-05-10 09:32
@yayajacky Your changes is work fine!
Please, create PR.
